- name: Create a group
  become: yes
  when: use_technical_group|bool
  group:
      name: "{{ technical_group|default('technical') }}"
      state: present
      gid: "{{ technical_group_id|default('1161') }}"

- name: "Create a technical account"
  become: yes
  when: use_technical_group|bool and use_technical_user|bool
  user:
      name: "{{ technical_account|default('tech.admin') }}"
      comment: "Technical account (deployment)"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      shell: /bin/bash
      password: "{{ technical_password }}"
      update_password: on_create
      createhome: yes
      uid: "{{ technical_account_id|default('1800') }}"
      groups: ["{{ technical_group|default('technical') }}", 'sudo']

- name: Enable all members of technical group to execute given project file as root
  become: yes
  lineinfile:
      dest: /etc/sudoers
      line: "%{{ technical_group|default('technical') }} ALL=(root) NOPASSWD: {{ technical_entrypoint|default('/project/make.sh') }}"
  when: enable_technical_entrypoint|bool and use_technical_group|bool and use_technical_user|bool
