- become: true
  become_user: "{{ user.login }}"
  block:
      - name: Copy private key to the user directory
        copy:
            src: "{{ user.ssh_priv_key }}"
            dest: "{{ user_home }}/.ssh/{{ user.ssh_priv_key | basename }}"
            mode: 0600
        when: "'ssh_priv_key' in user and user.ssh_priv_key"

      - name: Copy public key to the user directory
        copy:
            src: "{{ user.ssh_pub_key }}"
            dest: "{{ user_home }}/.ssh/{{ user.ssh_pub_key | basename }}"
            mode: 0600
        when: "'ssh_pub_key' in user and user.ssh_pub_key"

      - when: "'ssh_authorized_keys' in user and user.ssh_authorized_keys"
        block:
          - name: Added keys to authorized_keys
            authorized_key:
                user: "{{ user.login }}"
                state: present
                key: "{{ lookup('file', auth_key_path) }}"
                path: "{{ user_home }}/.ssh/authorized_keys"
            loop_control:
                loop_var: auth_key_path
            with_items: "{{ user.ssh_authorized_keys }}"

      - when: "'ssh_known_hosts' in user and user.ssh_known_hosts"
        block:
            - name: Add host to known_hosts
              become_user: "{{ user.login }}"
              become: true
              lineinfile:
                  path: "{{ user_home }}/.ssh/known_hosts"
                  regexp: "^{{ known_host }}"
                  line: "{{ known_host }}"
                  create: true
                  mode: 0600
              loop_control:
                  loop_var: known_host
              with_items: "{{ user.ssh_known_hosts }}"
