- name: Configure SSH daemon
  become: yes
  block:
      - set_fact:
            user_ssh_conf: "{{ lookup('template', 'user_ssh.conf.j2') }}"

      - name: Add user section to the sshd_config
        blockinfile:
            path: /etc/ssh/sshd_config
            block: "{{ user_ssh_conf }}"
            backup: yes
            validate: sshd -T -f %s
            marker: "# {mark} ANSIBLE MANAGED BLOCK {{ user.login }}"

      - name: Notify ssh about changes
        systemd:
            name: ssh
            state: reloaded
