
- set_fact:
      user_shell: "{{ user.shell | default('/bin/zsh') }}"

- set_fact:
      user_home: "{{ user.home | default('/home/' + user.login) }}"

- set_fact:
      sudo_group_name: '{% if "sudo_without_password" in user and user.sudo_without_password|bool %}sudonopasswd{% else %}sudo{% endif %}'

- name: "Create user {{ user.login }}"
  become: yes
  user:
      name: "{{ user.login }}"
      comment: "{{ user.section }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      shell: "{{ user_shell }}"
      password: "{{ user.password }}"
      update_password: on_create
      createhome: yes
      home: "{{ user_home }}"
      uid: "{{ user.uid }}"

- name: Add user to technical group
  when: use_technical_group|bool
  become: yes
  user:
      name: '{{ user.login }}'
      groups: "{{ technical_group|default('technical') }}"
      append: 'yes'

- name: Disable account if it was disabled in users.yml
  become: yes
  shell: "chage -E {{chage_past_date}} {{ user.login }}"
  when: user.disabled|bool

- name: Enable account if it was not disabled in users.yml
  become: yes
  shell: "chage -E {{chage_future_date}} {{ user.login }}"
  when: not user.disabled|bool

- name: Allow user to use sudo globally (if allowed)
  become: yes
  user:
    name: '{{ user.login }}'
    groups: "{{ sudo_group_name }}"
    append: yes
  when: user.global_sudo|bool

- name: Disallow user to use sudo (if disallowed)
  become: yes
  shell: "gpasswd -d {{ user.login }} sudo || true; gpasswd -d {{ user.login }} sudonopasswd || true"
  when: not user.global_sudo|bool

- name: Configure user SSH keys
  include: ssh-keys.yaml

- name: Configure ZSH
  include: zsh.yaml
  when: "'zsh' in (user.shell | default('/bin/zsh'))"

- name: Configure SSH daemon
  include: ssh-daemon.yaml

- name: Configure jail if necessary
  include: jail.yaml
  when: "'jailed' in user and user.jailed|bool"
