- name: Check if the user has customized zshrc
  stat: path="/home/{{ user.login }}/.zshrc"
  register: zshrc_file

- name: Creating a zshrc from template (if the user does not have already modified it)
  become: yes
  become_user: "{{ user.login }}"
  template:
      src: zshrc
      dest: "/home/{{ user.login }}/.zshrc"
  when: zshrc_file.stat.exists == False

- name: Clone oh-my-zsh
  become: yes
  become_user: "{{ user.login }}"
  git:
      repo: https://github.com/robbyrussell/oh-my-zsh
      dest: "/home/{{ user.login }}/.oh-my-zsh"
