ZSH=$HOME/.oh-my-zsh
ZSH_THEME="half-life"
DISABLE_AUTO_UPDATE="true"
plugins=(git symfony python vagrant ubuntu rsync composer systemd)
source $ZSH/oh-my-zsh.sh
export PATH=$HOME/bin:/usr/local/bin:$PATH
